# Netscape HTTP Cookie File
# https://curl.haxx.se/docs/http-cookies.html
# This file was generated by libcurl! Edit at your own risk.

#HttpOnly_localhost	FALSE	/	FALSE	0	test	s%3A-7-k1IxQecCiHNwLBx9FubOXgfYzt_Ty.TB2AEcqe4g6jTvyRwW8v8COQwKFXHQRt4EtA1jPdlzk
