# Netscape HTTP Cookie File
# https://curl.haxx.se/docs/http-cookies.html
# This file was generated by libcurl! Edit at your own risk.

#HttpOnly_localhost	FALSE	/	FALSE	0	test	s%3AAlqNyij5bi_5Rs6XiQi9XuGl1oyuN7PD.t8DZ5lCxLyuKMzm1Hg8BtdWHW%2FzUzNRAELcfu8rlYXE
